### ISSUE TITLE
关于 glm-4-voice-decoder 有两个疑惑，需要解答

### ISSUE THREAD

**Issue by choyakawa** [THUDM/GLM-4-Voice#68]
关于 glm-4-voice-decoder 有两个疑惑，需要解答

1. 在[glm-4-voice-decoder](https://huggingface.co/THUDM/glm-4-voice-decoder)的配置文件中，似乎有一个新训练的LM，这部分是什么？与CosyVoice的应该是不同的，而并没有在开源权重仓库里面看到。如果是WhisperVQ token直接在这里和输出对齐，这部分在训练时为什么还会有一个LLM呢？

```yaml
llm: !new:cosyvoice.llm.llm.TransformerLM
    text_encoder_input_size: !ref <text_encoder_input_size>
    llm_input_size: !ref <llm_input_size>
    llm_output_size: !ref <llm_output_size>
    text_token_size: 51866
    speech_token_size: 4096
    length_normalized_loss: True
    lsm_weight: 0
    spk_embed_dim: !ref <spk_embed_dim>
    text_encoder: !new:cosyvoice.transformer.encoder.ConformerEncoder
        input_size: !ref <text_encoder_input_size>
        output_size: 1024
        attention_heads: 8
        linear_units: 2048
        num_blocks: 3
        dropout_rate: 0.1
        positional_dropout_rate: 0.1
        attention_dropout_rate: 0
        normalize_before: True
        input_layer: 'linear'
        pos_enc_layer_type: 'rel_pos_espnet'
        selfattention_layer_type: 'rel_selfattn'
        use_cnn_module: False
        macaron_style: False
        use_dynamic_chunk: False
        use_dynamic_left_chunk: False
        static_chunk_size: 1
    llm: !new:cosyvoice.transformer.encoder.TransformerEncoder
        input_size: !ref <llm_input_size>
        output_size: !ref <llm_output_size>
        attention_heads: 8
        linear_units: 2048
        num_blocks: 7
        dropout_rate: 0.1
        positional_dropout_rate: 0.1
        attention_dropout_rate: 0
        input_layer: 'linear_legacy'
        pos_enc_layer_type: 'rel_pos_espnet'
        selfattention_layer_type: 'rel_selfattn'
        static_chunk_size: 1
```

2. 这个decoder的spk_embed_affine_layer有什么作用？似乎并没有训练多spk，embedding对输出似乎没有任何影响。
