### ISSUE TITLE
使用zhipuai/glm-4-voice:0.1 docker 无法运行

### ISSUE THREAD

**Issue by soloHeroo** [THUDM/GLM-4-Voice#93]
使用zhipuai/glm-4-voice:0.1 docker 无法运行，也没有日志输出

**Comment by syl0735** [comment]
他这个镜像仅仅是一个安装好依赖的python环境

**Comment by zhnglicho** [comment]
```
version: "3"
services:
  glm-4-voice-serving:
    image: zhipuai/glm-4-voice:0.1
    container_name: glm-4-voice
    restart: always
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    command:
      - tail
      - -f
      - model_server.py
    volumes:
      - /home/user/GLM-4-Voice:/tmp/glm-4-voice/
    ports:
      - 8080:8080
    environment:
      HF_ENDPOINT: "https://hf-mirror.com"
```
这里是一个运行docker 的 compose 示例文件， 用以启动docker 镜像， 进入镜像后你可以运行命令启动服务
